# Generated by Django 4.2.29 on 2026-03-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_shades'),
        ('profiles', '0001_initial'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user_profile', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='shade',
        ),
    ]
