# Generated by Django 4.2.29 on 2026-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_shades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shades',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
